## importing libraries

In [ ]:
from pathlib import Path as Path
import pandas as pd
import numpy as np

## importing datasets using pathlib

In [ ]:
data_path = Path(
    "/Users/rohankhanna/Documents/track3_agritech_dataset_files"
)

df_arrivals = pd.read_csv(
    data_path / "track3_mandi_arrivals.csv"
)

df_master = pd.read_csv(
    data_path / "track3_mandi_master.csv"
)

## Previewing each dataset

In [11]:
display(df_arrivals.head())
display(df_master.head())
display(df_prices.head())
display(df_transport.head())
display(df_weather.head())

,arrival_id,date,mandi_id,crop_name,variety,arrival_quantity,unit,farmer_count
0,ARR0012424,06-04-2026,MANDI026,गेहूं,Hybrid,44.841,T,128.0
1,ARR0008271,2026-06-02,MANDI014,Gehun,HD-2967,332.54,Qtl,33.0
2,ARR0022724,08-16-2026,056,Kanak,HD-2967,415.88 qtl,NaN,NaN
3,ARR0012573,06-24-2026,MANDI019,Maize,NaN,-107.13,KG,112.0
4,ARR0012098,09.08.2026,mandi050,Corn,Premium,-331.59,Qtl,NaN

,mandi_id,mandi_name,district,state,mandi_type,total_area_acres
0,MANDI001,Hyderabad Mandi,ludhiana,Punjab,Private,11.0
1,MANDI006,Kochi Mandi,Amritsar,Punjab,Direct,34.0
2,MANDI037,Jorhat Grain Market,Kurukshetra,Haryana,APMC,NaN
3,MANDI046,Baranagar Market,NaN,Uttar Pradesh,Private,13.0
4,MANDI014,Bathinda Grain Market,Patiala,Punjab,PRIVATE,25.0

,record_id,date,mandi_id,district,crop_name,min_price,max_price,modal_price,msp
0,PR001650,2026/07/26,MANDI005,NaN,Kapas,6850.985817820893,"₹7,570.17",7210.58,"₹6,620.00"
1,PR000246,2026-07-17,MANDI028,Fatehabad,कपास,"₹6,944.79",7654.18,"Rs. 7,299",
2,PR010091,09.01.2026,MANDI011,Jalandhar,Dhaan,"Rs. 1,857",2013.18,"₹1,935.06","INR 2,183"
3,PR000982,2026/05/24,M012,Ferozepur,corn,"₹1,873.34","Rs. 1,986","Rs. 1,930","Rs. 2,090"
4,PR001708,18/08/2026,013,Karnal,Cotton,"5,878.62/-",6574.283051769212,6226.45,"Rs. 6,620"

,trip_id,mandi_id,destination_warehouse,departure_time,arrival_time,transit_hours,distance,distance_unit,vehicle_no,driver_id
0,TRP006374,MANDI050,WH-Central,2026-04-30T20:08:22,01/05/2026 05:26,9.3,305.714532,miles,NaN,DRV264
1,TRP008869,MANDI029,WH-West,04-10-2026 04:15 AM,10/04/2026 09:51,NaN,263.5,km,NaN,DRV540
2,TRP000674,MANDI024,WH-South,18/07/2026 16:34,07-18-2026 10:46 PM,6.2,276.5,km,UP 50 BC 6882,DRV722
3,TRP000036,MANDI-042,WH-Central,08-13-2026 06:21 AM,14/08/2026,19.7,1070.7,km,RJ-52-CD-3274,DRV103
4,TRP008288,mandi_019,WH-South,07-30-2026 10:51 PM,07-31-2026 03:57 PM,17.1,728.9,km,DL-73-DF-1458,NaN

,sensor_id,timestamp,temperature,temp_unit,rainfall,rain_unit,humidity_percent
0,SEN047,28/08/2026,68,f,43.80,mm,46.0
1,SEN034,2026-07-03 07:08:18 IST,85.3,°F,1.88,in,55.0
2,SEN020,NaN,18.9,Celsius,19.90,MM,NaN
3,SEN035,2026-07-09 11:08:41 UTC,71.8,Fahrenheit,0.91,inch,49.0
4,SEN048,2026-06-09 13:06:26 IST,39.8°C,NaN,43.90,mm,81.0

## Checking structure and missing values in the dataset

In [ ]:
datasets = {
    "Arrivals": df_arrivals,
    "Mandi Master": df_master,
    "Prices": df_prices,
    "Transport": df_transport,
    "Weather": df_weather
}

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(name)
    print(f"Rows: {df.shape[0]:,} | Columns: {df.shape[1]}")
    print(f"Extra exact duplicate rows: {df.duplicated().sum():,}")


    inspection = df.replace(r"^\s*$", pd.NA, regex=True)

    report = pd.DataFrame({
        "Data type": df.dtypes.astype(str),
        "Missing values": inspection.isna().sum(),
        "Missing (%)": (
            inspection.isna().mean() * 100
        ).round(2)
    })

    display(report)

==================================================
Arrivals
Rows: 25,750 | Columns: 8
Extra exact duplicate rows: 750

                 Data type  Missing values  Missing (%)
arrival_id             str             484         1.88
date                   str               0         0.00
mandi_id               str               0         0.00
crop_name              str               0         0.00
variety                str            3735        14.50
arrival_quantity       str               0         0.00
unit                   str            5143        19.97
farmer_count       float64            3899        15.14

==================================================
Mandi Master
Rows: 60 | Columns: 6
Extra exact duplicate rows: 3

                 Data type  Missing values  Missing (%)
mandi_id               str               0         0.00
mandi_name             str               0         0.00
district               str               4         6.67
state                  str               4         6.67
mandi_type             str              11        18.33
total_area_acres   float64               6        10.00

==================================================
Prices
Rows: 12,000 | Columns: 9
Extra exact duplicate rows: 0

            Data type  Missing values  Missing (%)
record_id         str               0         0.00
date              str               0         0.00
mandi_id          str            1235        10.29
district          str            1546        12.88
crop_name         str               0         0.00
min_price      object             598         4.98
max_price      object             598         4.98
modal_price    object             610         5.08
msp            object            2377        19.81

==================================================
Transport
Rows: 10,400 | Columns: 10
Extra exact duplicate rows: 400

                      Data type  Missing values  Missing (%)
trip_id                     str               0         0.00
mandi_id                    str               0         0.00
destination_warehouse       str               0         0.00
departure_time              str               0         0.00
arrival_time                str            1053        10.12
transit_hours               str             518         4.98
distance                    str               0         0.00
distance_unit               str            1032         9.92
vehicle_no                  str            1622        15.60
driver_id                   str            1551        14.91

==================================================
Weather
Rows: 15,000 | Columns: 7
Extra exact duplicate rows: 0

                 Data type  Missing values  Missing (%)
sensor_id              str               0         0.00
timestamp              str            1555        10.37
temperature         object               0         0.00
temp_unit              str            2263        15.09
rainfall           float64             791         5.27
rain_unit              str             791         5.27
humidity_percent   float64            1500        10.00

## Inspecting Mandi Master before cleaning it

In [14]:

df_master_clean = df_master.copy(deep=True)


display(df_master_clean)

# Inspect the exact spellings and formats.
# repr() makes spaces and empty strings easier to see.
for column in ["mandi_id", "district", "state", "mandi_type"]:
    print(f"\nUnique values in {column}:")
    print([repr(value) for value in df_master_clean[column].unique()])

# Show every occurrence of an exact duplicate.
print("\nExact duplicate groups:")
display(
    df_master_clean[
        df_master_clean.duplicated(keep=False)
    ].sort_values("mandi_id")
)

,mandi_id,mandi_name,district,state,mandi_type,total_area_acres
0,MANDI001,Hyderabad Mandi,ludhiana,Punjab,Private,11.0
1,MANDI006,Kochi Mandi,Amritsar,Punjab,Direct,34.0
2,MANDI037,Jorhat Grain Market,Kurukshetra,Haryana,APMC,NaN
3,MANDI046,Baranagar Market,NaN,Uttar Pradesh,Private,13.0
4,MANDI014,Bathinda Grain Market,Patiala,Punjab,PRIVATE,25.0
5,MANDI055,Chandigarh APMC,Bareilly,Uttar Pradesh,apmc,12.0
6,MANDI034,Ludhiana Grain Market,Ambala,Haryana,NaN,11.0
7,MANDI049,Machilipatnam Mandi,Muzaffarnagar,Uttar Pradesh,Private,39.0
8,MANDI013,Aurangabad Market,Patiala,Punjab,Private,25.0
9,MANDI001,Hyderabad Mandi,ludhiana,Punjab,Private,11.0
10,MANDI047,Orai Market,Muzaffarnagar,Uttar Pradesh,APMC,NaN
11,MANDI051,Gulbarga Market,Saharanpur,Uttar Pradesh,Private,11.0
12,MANDI032,Chapra Grain Market,NaN,Haryana,PRIVATE,20.0
13,MANDI004,Khandwa Grain Market,Ludhiana,Punjab,APMC,15.0
14,MANDI053,Panihati Market,Saharanpur,Uttar Pradesh,APMC,NaN
15,MANDI018,Jaunpur Mandi,MOGA,Punjab,NaN,9.0
16,MANDI009,Jamshedpur APMC,Jalandhar,Punjab,apmc,28.0
17,MANDI007,Nashik Mandi,Amritsar,Punjab,PRIVATE,45.0
18,MANDI041,Gurgaon Grain Market,FATEHABAD,Haryana,APMC,39.0
19,MANDI005,Bhilwara Grain Market,Amritsar,Punjab,Direct,29.0
20,MANDI044,Dehri Mandi,Agra,Uttar Pradesh,APMC,41.0
21,MANDI020,Kadapa Mandi,Ferozepur,Punjab,Direct,26.0
22,MANDI035,Guntakal Mandi,Ambala,Haryana,APMC,17.0
23,MANDI006,Kochi Mandi,Amritsar,Punjab,Direct,34.0
24,MANDI026,Tadipatri Mandi,Hisar,Haryana,Private,35.0
25,MANDI057,Gorakhpur APMC,Bareilly,NaN,Direct,7.0
26,MANDI016,Kulti APMC,Bathinda,Punjab,NaN,42.0
27,MANDI028,Machilipatnam APMC,Hisar,Haryana,NaN,33.0
28,MANDI010,Dhule APMC,Jalandhar,Punjab,Direct,48.0
29,MANDI031,Nangloi Jat Mandi,Sirsa,Haryana,APMC,22.0
30,MANDI027,Kochi APMC,Hisar,Haryana,apmc,39.0
31,MANDI017,Parbhani Market,NaN,Punjab,PRIVATE,8.0
32,MANDI025,Dindigul APMC,karnal,Haryana,APMC,NaN
33,MANDI056,Bilaspur Mandi,Bareilly,Uttar Pradesh,Private,28.0
34,MANDI012,Gaya Grain Market,Patiala,Punjab,NaN,48.0
35,MANDI033,South Dumdum Grain Market,AMBALA,Haryana,apmc,31.0
36,MANDI054,Nangloi Jat Grain Market,Saharanpur,NaN,Direct,45.0
37,MANDI042,Erode Mandi,Fatehabad,Haryana,PRIVATE,38.0
38,MANDI038,Jalandhar Mandi,Kurukshetra,Haryana,Private,36.0
39,MANDI030,Patiala APMC,Sirsa,NaN,NaN,19.0
40,MANDI045,Farrukhabad Mandi,Meerut,Uttar Pradesh,PRIVATE,25.0
41,MANDI002,Solapur Mandi,Ludhiana,NaN,APMC,37.0
42,MANDI022,Eluru APMC,Karnal,Haryana,NaN,45.0
43,MANDI003,Vijayawada Mandi,Ludhiana,Punjab,NaN,19.0
44,MANDI048,Chittoor Mandi,muzaffarnagar,Uttar Pradesh,Direct,27.0
45,MANDI040,Jodhpur Market,Fatehabad,Haryana,Direct,40.0
46,MANDI036,Mysore Grain Market,KURUKSHETRA,Haryana,apmc,9.0
47,MANDI024,Jaipur Mandi,Karnal,Haryana,APMC,24.0
48,MANDI050,Durg Market,Muzaffarnagar,Uttar Pradesh,NaN,47.0
49,MANDI011,Arrah Mandi,Patiala,Punjab,NaN,34.0
50,MANDI023,Panihati APMC,KARNAL,Haryana,PRIVATE,38.0
51,MANDI019,Karimnagar Grain Market,Moga,Punjab,PRIVATE,40.0
52,MANDI031,Nangloi Jat Mandi,Sirsa,Haryana,APMC,22.0
53,MANDI021,Guna Mandi,Ferozepur,Punjab,APMC,21.0
54,MANDI008,Bijapur Market,Amritsar,Punjab,APMC,23.0
55,MANDI043,Danapur Mandi,Agra,Uttar Pradesh,Private,NaN
56,MANDI015,Amravati Grain Market,Bathinda,Punjab,apmc,13.0
57,MANDI029,Asansol Grain Market,SIRSA,Haryana,Direct,NaN
58,MANDI052,Kakinada APMC,Saharanpur,Uttar Pradesh,NaN,48.0
59,MANDI039,Anand Grain Market,NaN,Haryana,APMC,5.0

Unique values in mandi_id:
["'MANDI001'", "'MANDI006'", "'MANDI037'", "'MANDI046'", "'MANDI014'", "'MANDI055'", "'MANDI034'", "'MANDI049'", "'MANDI013'", "'MANDI047'", "'MANDI051'", "'MANDI032'", "'MANDI004'", "'MANDI053'", "'MANDI018'", "'MANDI009'", "'MANDI007'", "'MANDI041'", "'MANDI005'", "'MANDI044'", "'MANDI020'", "'MANDI035'", "'MANDI026'", "'MANDI057'", "'MANDI016'", "'MANDI028'", "'MANDI010'", "'MANDI031'", "'MANDI027'", "'MANDI017'", "'MANDI025'", "'MANDI056'", "'MANDI012'", "'MANDI033'", "'MANDI054'", "'MANDI042'", "'MANDI038'", "'MANDI030'", "'MANDI045'", "'MANDI002'", "'MANDI022'", "'MANDI003'", "'MANDI048'", "'MANDI040'", "'MANDI036'", "'MANDI024'", "'MANDI050'", "'MANDI011'", "'MANDI023'", "'MANDI019'", "'MANDI021'", "'MANDI008'", "'MANDI043'", "'MANDI015'", "'MANDI029'", "'MANDI052'", "'MANDI039'"]

Unique values in district:
["'ludhiana'", "'Amritsar'", "'Kurukshetra'", 'nan', "'Patiala'", "'Bareilly'", "'Ambala'", "'Muzaffarnagar'", "'Saharanpur'", "'Ludhiana'", "'MOGA'", "'Jalandhar'", "'FATEHABAD'", "'Agra'", "'Ferozepur'", "'Hisar'", "'Bathinda'", "'Sirsa'", "'karnal'", "'AMBALA'", "'Fatehabad'", "'Meerut'", "'Karnal'", "'muzaffarnagar'", "'KURUKSHETRA'", "'KARNAL'", "'Moga'", "'SIRSA'"]

Unique values in state:
["'Punjab'", "'Haryana'", "'Uttar Pradesh'", 'nan']

Unique values in mandi_type:
["'Private'", "'Direct'", "'APMC'", "'PRIVATE'", "'apmc'", 'nan']

Exact duplicate groups:

,mandi_id,mandi_name,district,state,mandi_type,total_area_acres
0,MANDI001,Hyderabad Mandi,ludhiana,Punjab,Private,11.0
9,MANDI001,Hyderabad Mandi,ludhiana,Punjab,Private,11.0
1,MANDI006,Kochi Mandi,Amritsar,Punjab,Direct,34.0
23,MANDI006,Kochi Mandi,Amritsar,Punjab,Direct,34.0
29,MANDI031,Nangloi Jat Mandi,Sirsa,Haryana,APMC,22.0
52,MANDI031,Nangloi Jat Mandi,Sirsa,Haryana,APMC,22.0

## Cleaning the copy of our data

In [15]:
# Use only records with both district and state present.
known_locations = (
    df_master_clean[["district", "state"]]
    .dropna()
    .drop_duplicates()
)

# Check whether any district is associated with multiple states.
states_per_district = (
    known_locations.groupby("district")["state"].nunique()
)

# Only use districts with exactly one observed state.
safe_districts = states_per_district[
    states_per_district == 1
].index

district_to_state = (
    known_locations[
        known_locations["district"].isin(safe_districts)
    ]
    .set_index("district")["state"]
)

# Identify missing states that can be recovered.
suggested_state = df_master_clean["district"].map(
    district_to_state
)

fill_mask = (
    df_master_clean["state"].isna()
    & suggested_state.notna()
)

# Keep a record of each correction.
state_fill_log = df_master_clean.loc[
    fill_mask, ["mandi_id", "district", "state"]
].copy()

state_fill_log = state_fill_log.rename(
    columns={"state": "original_state"}
)

state_fill_log["filled_state"] = suggested_state.loc[fill_mask]
state_fill_log["reason"] = (
    "Unique district-to-state relationship in mandi master"
)

# Fill only the recoverable missing states.
df_master_clean.loc[fill_mask, "state"] = (
    suggested_state.loc[fill_mask]
)

print("Missing states filled:", int(fill_mask.sum()))
print("Missing states remaining:", df_master_clean["state"].isna().sum())

display(state_fill_log)

Missing states filled: 4
Missing states remaining: 0

,mandi_id,district,original_state,filled_state,reason
25,MANDI057,Bareilly,NaN,Uttar Pradesh,Unique district-to-state relationship in mandi...
36,MANDI054,Saharanpur,NaN,Uttar Pradesh,Unique district-to-state relationship in mandi...
39,MANDI030,Sirsa,NaN,Haryana,Unique district-to-state relationship in mandi...
41,MANDI002,Ludhiana,NaN,Punjab,Unique district-to-state relationship in mandi...

## check whether the prices dataset can help recover the four missing districts. Prices contain both mandi_id and district, but we must check for conflicting mappings before using them.

In [16]:
# Identify mandis whose district is still missing.
missing_districts = df_master_clean.loc[
    df_master_clean["district"].isna(),
    ["mandi_id", "mandi_name", "state"]
]

display(missing_districts)

# Prepare a temporary lookup from prices.
price_locations = df_prices[["mandi_id", "district"]].copy()

# Normalize ID formats such as MANDI-001, mandi_001 and M001.
id_text = (
    price_locations["mandi_id"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.replace(r"[\s_-]+", "", regex=True)
)

# Accept only a complete recognized ID pattern.
id_number = id_text.str.extract(
    r"^(?:MANDI|M)?(\d{1,3})$",
    expand=False
)

price_locations["mandi_id"] = (
    "MANDI" + id_number.str.zfill(3)
)

price_locations["district"] = (
    price_locations["district"]
    .astype("string")
    .str.strip()
    .str.title()
    .replace("", pd.NA)
)

# Inspect district evidence for only the affected mandis.
district_evidence = (
    price_locations.loc[
        price_locations["mandi_id"].isin(
            missing_districts["mandi_id"]
        )
    ]
    .dropna(subset=["mandi_id", "district"])
    .groupby(["mandi_id", "district"])
    .size()
    .reset_index(name="price_record_count")
    .sort_values(
        ["mandi_id", "price_record_count"],
        ascending=[True, False]
    )
)

display(district_evidence)

    mandi_id           mandi_name          state
3   MANDI046     Baranagar Market  Uttar Pradesh
12  MANDI032  Chapra Grain Market        Haryana
31  MANDI017      Parbhani Market         Punjab
59  MANDI039   Anand Grain Market        Haryana

    mandi_id     district  price_record_count
1   MANDI017     Amritsar                  19
2   MANDI017     Bathinda                  17
10  MANDI017         Moga                  16
3   MANDI017    Fatehabad                  15
11  MANDI017      Patiala                  15
4   MANDI017    Ferozepur                  14
5   MANDI017        Hisar                  14
9   MANDI017     Ludhiana                  14
6   MANDI017    Jalandhar                  12
12  MANDI017        Sirsa                  12
8   MANDI017  Kurukshetra                   9
0   MANDI017       Ambala                   7
7   MANDI017       Karnal                   4
22  MANDI032     Ludhiana                  27
20  MANDI032       Karnal                  22
16  MANDI032    Fatehabad                  17
14  MANDI032     Amritsar                  16
21  MANDI032  Kurukshetra                  14
18  MANDI032        Hisar                  13
25  MANDI032        Sirsa                  13
13  MANDI032       Ambala                  12
15  MANDI032     Bathinda                  10
19  MANDI032    Jalandhar                   9
23  MANDI032         Moga                   9
24  MANDI032      Patiala                   7
17  MANDI032    Ferozepur                   6
32  MANDI039    Jalandhar                  17
36  MANDI039         Moga                  17
27  MANDI039     Amritsar                  16
26  MANDI039       Ambala                  15
33  MANDI039       Karnal                  15
29  MANDI039    Fatehabad                  14
38  MANDI039        Sirsa                  13
30  MANDI039    Ferozepur                  12
34  MANDI039  Kurukshetra                  12
37  MANDI039      Patiala                  12
28  MANDI039     Bathinda                  11
31  MANDI039        Hisar                  11
35  MANDI039     Ludhiana                   9
39  MANDI046       Ambala                  18
45  MANDI046    Jalandhar                  16
49  MANDI046         Moga                  14
50  MANDI046      Patiala                  14
42  MANDI046    Fatehabad                  12
48  MANDI046     Ludhiana                  12
51  MANDI046        Sirsa                  12
41  MANDI046     Bathinda                  11
40  MANDI046     Amritsar                  10
43  MANDI046    Ferozepur                  10
47  MANDI046  Kurukshetra                   9
46  MANDI046       Karnal                   8
44  MANDI046        Hisar                   7

## This shows we cannot reliably recover these districts as they have confliciting evidences we are keeping this four districts as missing and flag them as unresolved

In [17]:
df_master_clean["district_status"] = "Present in master"

missing_mask = df_master_clean["district"].isna()

df_master_clean.loc[
    missing_mask, "district_status"
] = "Unresolved: conflicting price districts"

district_issue_log = df_master_clean.loc[
    missing_mask,
    ["mandi_id", "mandi_name", "state", "district_status"]
].copy()

display(district_issue_log)

,mandi_id,mandi_name,state,district_status
3,MANDI046,Baranagar Market,Uttar Pradesh,Unresolved: conflicting price districts
12,MANDI032,Chapra Grain Market,Haryana,Unresolved: conflicting price districts
31,MANDI017,Parbhani Market,Punjab,Unresolved: conflicting price districts
59,MANDI039,Anand Grain Market,Haryana,Unresolved: conflicting price districts

## Checking the remaining numeric field

In [18]:
area_raw = df_master_clean["total_area_acres"]

area_numeric = pd.to_numeric(area_raw, errors="coerce")

df_master_clean["area_status"] = "Valid"

df_master_clean.loc[
    area_raw.isna(), "area_status"
] = "Missing"

df_master_clean.loc[
    area_raw.notna() & area_numeric.isna(),
    "area_status"
] = "Invalid numeric value"

df_master_clean.loc[
    area_numeric.le(0), "area_status"
] = "Nonpositive area: review"

df_master_clean["total_area_acres"] = area_numeric

display(
    df_master_clean["area_status"]
    .value_counts()
    .to_frame("mandi_count")
)

             mandi_count
area_status
Valid                 54
Missing                6

## Remove identical rows while preserving your existing cleaning.

In [ ]:

df_master_clean = (
    df_master_clean
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Rows after removing duplicates:", len(df_master_clean))

Rows after removing duplicates: 57

In [27]:
assert len(df_master_clean) == 57, "Expected 57 rows."

assert df_master_clean["mandi_id"].notna().all(), (
    "Missing mandi IDs found."
)

assert df_master_clean["mandi_id"].is_unique, (
    "Duplicate mandi IDs found."
)

assert df_master_clean["mandi_id"].str.fullmatch(
    r"MANDI\d{3}", na=False
).all(), "Unexpected mandi ID format."

assert df_master_clean["state"].notna().all(), (
    "Missing states remain."
)

print("Master validation passed.")

display(
    df_master_clean.isna().sum().to_frame("Missing count")
)

Master validation passed.

                  Missing count
mandi_id                      0
mandi_name                    0
district                      4
state                         0
mandi_type                   11
total_area_acres              6
district_status               0
area_status                   0

## Exporting CSV and filling missing values as NA

In [29]:
from pathlib import Path

output_folder = Path(
    "/Users/rohankhanna/Documents/datathon/cleaned_data"
)
output_folder.mkdir(parents=True, exist_ok=True)

output_file = output_folder / "mandi_master_cleaned.csv"

df_master_clean.to_csv(
    output_file,
    index=False,
    na_rep="NA",
    encoding="utf-8-sig"
)

print("File saved:", output_file)

File saved: /Users/rohankhanna/Documents/datathon/cleaned_data/mandi_master_cleaned.csv